(TeX-add-style-hook
 "Background"
 (lambda ()
   (LaTeX-add-labels
    "BackgroundKnowledgeCh"
    "eq:unit_vol_prob_axiom"
    "eq:non_neg_of_prob"
    "eq:sum_rule"
    "eq:product_rule"
    "eq:Bayes_thm"
    "eq:expectation"
    "eq:covariance"
    "eq:Gaussian_dist"
    "eq:sample_x"
    "eq:join_dist_Gaussian"
    "eq:twin_joint_diag_cov"
    "eq:likelihood"
    "eq:log-likelihood"
    "eq:dir_graph_model_dist"
    "eq:latent_var_model"
    "eq:AI_optimal_element"
    "eq:MLP_output"
    "eq:MLP_base_case"
    "eq:logistic_function"
    "eq:conditional_language_probability"
    "eq:one_hot_encoding"
    "eq:cosine_similarity"
    "fig:encoder_decoder"
    "eq:GD_update"
    "eq:SGD_update"
    "ADAM"))
 :latex)

